# Docker Compose para Fascinante Digital
# Configuración optimizada para desarrollo

services:
  # ===========================================
  # Servicio Principal - Next.js App
  # ===========================================
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: fascinante-digital-web
    ports:
      - "3000:3000"
    volumes:
      # Hot reload para desarrollo
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true  # Para hot reload en Windows
    restart: unless-stopped

  # ===========================================
  # Nginx - Reverse Proxy (Solo para producción)
  # ===========================================
  nginx:
    image: nginx:alpine
    container_name: fascinante-digital-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    profiles:
      - production  # Solo se ejecuta con --profile production
    depends_on:
      - web
